apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ead-ca2
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

        env:
        - name: DATABASE_URL
          value: "mongodb+srv://ead2024:ead2024.@ead-2023-24.lpclwdo.mongodb.net/?retryWrites=true&w=majority"
        - name: DATABASE_NAME
          value: "ead_ca2"
        - name: DATABASE_COLLECTION
          value: "ead_2024"

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5