apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ead-ca2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: YOUR_DOCKERHUB_USERNAME/frontend-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22137

        livenessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 10
          periodSeconds: 5